version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fyxi-backend
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fyxi-frontend
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
